defaults:
  - ./@train: medvqa
  - ./@test: medvqa
  - _self_

train:
  root_dir: "${oc.env:VQARAD_ROOT_DIR}"
  num_ans_candidates: 458
  split: train
  tokenizer:
    _target_: vqa.dataset_vqa.Dictionary.load_from_file
    path: "${oc.env:VQARAD_ROOT_DIR}/dictionary.pkl"
    context_length: 12

test:
  root_dir: "${oc.env:VQARAD_ROOT_DIR}"
  num_ans_candidates: 458
  split: test
  tokenizer:
    _target_: vqa.dataset_vqa.Dictionary.load_from_file
    path: "${oc.env:VQARAD_ROOT_DIR}/dictionary.pkl"
    context_length: 12
